# Readonlytest config
readonlyrest:
  enable: true

  #ssl:
    #enable: true
    # keystore_file: "/tmp/ssl/self.jks"
    # keystore_pass: KEYSTORE_PASSWORD
    # key_pass: KEY_PASS

  response_if_req_forbidden: Dashboard access is forbidden. Invalid credentials.
  #rest.action.multi.allow_explicit_index: false

  ldaps:
    - name: ldap
      host: "ldap.eionet.europa.eu"
      port: 389
      ssl_enabled: false
      ssl_trust_all_certs: true
#        bind_dn: "cn=admin,dc=example,dc=com"
#        bind_password: "password"
      search_user_base_DN: "ou=Users,o=EIONET,l=Europe"
      user_id_attribute: "uid"
      search_groups_base_DN: "ou=Groups,o=EIONET,l=Europe"
      unique_member_attribute: "uniqueMember"
      connection_pool_size: 10
      connection_timeout_in_sec: 10
      request_timeout_in_sec: 10
      cache_ttl_in_sec: 60

  access_control_rules:
  #- name: Accept all request from localhost
  #  type: allow
  #  hosts: [127.0.0.1, localhost]
  #  verbosity: info


  - name: Check_mk
    type: allow
    #hosts: [CHECKHEALTH]
    actions: ["cluster:monitor/health"]
    verbosity: error

  - name: public_access
    type: allow
    indices: ["records", "indicators"]
    verbosity: error

  # We trust Kibana's server side process, full access granted via HTTP authentication
  - name: "::KIBANA-SRV::"
    groups: ["kibana_srv"]
    verbosity: error

  - name: Kibana RW
    groups: ["kibana_rw"]
    kibana_access: rw
    kibana_index: .dashboards
    verbosity: error

  - name: Kibana LDAP RW
    ldap_authentication:
      name: "ldap"
    ldap_authorization:
      name: "ldap"
      groups: ["extranet"]
    kibana_access: rw
    kibana_index: .dashboards
    verbosity: info

  - name: Kibana_RO
#    groups: ["kibana_ro"]
    type: allow
    kibana_access: ro
    kibana_index: .dashboards
    verbosity: error

#  - name: Kibana_RO_strict
#    groups: ["kibana_ro_strict"]
#    type: allow
#    kibana_access: ro_strict
#    kibana_index: .dashboards
#    #indices: [".kibana"]
#    verbosity: error


  users:

  - username: kibana_rw
    auth_key: changeme:changeme
    groups: ["kibana_rw"]

#  - username: kibana_ro
#    auth_key: visitor:visitor
#    groups: ["kibana_ro"]

  - username: kibana_server
    # auth_key is good for testing, but replace it with `auth_key_sha256`!
    auth_key: kibana_server:password
    groups: ["kibana_srv"]
